
mensagens = [
    "Olá! Temos novidades incríveis para você.",
    "Aproveite nossas ofertas exclusivas hoje!",
    "Sentimos sua falta! Volte e confira o que preparamos.",
    "Você foi selecionado para uma condição especial!",
    "Temos uma surpresa esperando por você.",
    "Faça seu dinheiro trabalhar por você com as melhores oportunidades de investimento do banco.",
    "Invista hoje e conquiste mais liberdade financeira amanhã.",
    "Seu futuro merece segurança — comece a investir com quem entende do assunto.",
    "Transforme pequenos valores em grandes conquistas com investimentos inteligentes.",
    "Aproveite rendimentos competitivos sem abrir mão da segurança.",
    "Dê o próximo passo na sua vida financeira com opções de investimento sob medida.",
    "Seu dinheiro parado perde valor — invista e veja ele crescer.",
    "Conte com a solidez de um banco para investir com confiança.",
    "Invista com praticidade, direto pelo app, sem complicações.",
    "Chegou a hora de fazer seu dinheiro render mais do que na poupança.",
    "Invista com quem oferece transparência e confiança em cada etapa.",
    "Construa um futuro tranquilo começando a investir hoje mesmo.",
    "Tenha acesso a produtos exclusivos e aumente seu potencial de ganhos.",
    "Segurança, rentabilidade e praticidade em um só lugar.",
    "Diversifique seus investimentos e aumente suas oportunidades de lucro.",
    "Planeje seus sonhos com investimentos que acompanham seus objetivos.",
    "Mais controle, mais rendimento, mais tranquilidade para você.",
    "Invista com estratégia e alcance seus objetivos mais rápido.",
    "Seu sucesso financeiro começa com uma boa decisão: investir.",
    "Aproveite as vantagens de investir com um banco que pensa no seu futuro.",
]

